"use client";

import { FormEvent, useEffect, useState } from "react";
import { api, json, mediaUrl } from "../lib/api";
import type { Child, User } from "../types";

export function ProfileFeature({ user, children, onLogout, onUserChanged, notify }: { user: User; children: Child[]; onLogout: () => void; onUserChanged: (user: User) => void; notify: (text: string, tone?: "success" | "error") => void }) {
  const [settings, setSettings] = useState({ booking: true, waitlist: true, notices: true, chat: true, quietStart: "", quietEnd: "" });
  useEffect(() => { api<{ settings: typeof settings }>("/api/v1/notifications").then((data) => setSettings({ ...settings, ...data.settings })).catch(() => undefined); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  async function saveProfile(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { const result = await api<{ profile: User }>("/api/v1/profile", json("PATCH", { name: form.get("name"), phone: form.get("phone") })); onUserChanged(result.profile); notify("개인정보를 저장했습니다."); } catch (error) { notify(error instanceof Error ? error.message : "저장하지 못했습니다.", "error"); } }
  async function changePassword(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await api("/api/v1/profile", json("PUT", { currentPassword: form.get("currentPassword"), newPassword: form.get("newPassword") })); notify("비밀번호를 변경했습니다."); event.currentTarget.reset(); } catch (error) { notify(error instanceof Error ? error.message : "변경하지 못했습니다.", "error"); } }
  async function saveNotifications(next = settings) { try { await api("/api/v1/notifications", json("PUT", next)); setSettings(next); notify("알림 설정을 저장했습니다."); } catch (error) { notify(error instanceof Error ? error.message : "알림 설정을 저장하지 못했습니다.", "error"); } }
  async function uploadProfile(file?: File) { if (!file) return; const body = new FormData(); body.append("file", file); body.append("scope", "profile"); try { const result = await api<{ key: string }>("/api/v1/media", { method: "POST", body }); const updated = await api<{ profile: User }>("/api/v1/profile", json("PATCH", { name: user.name, phone: user.phone, profileImageKey: result.key })); onUserChanged(updated.profile); notify("프로필 사진을 변경했습니다."); } catch (error) { notify(error instanceof Error ? error.message : "사진을 등록하지 못했습니다.", "error"); } }
  return <section className="page-section narrow"><header className="profile-header"><label className="profile-avatar">{user.profileImageKey ? <img src={mediaUrl(user.profileImageKey)} alt="프로필" /> : <span>{user.name.slice(0, 1)}</span>}<input type="file" accept="image/*" onChange={(event) => uploadProfile(event.target.files?.[0])} /><small>사진 변경</small></label><div><p className="eyebrow dark">MY SLOW TRAIN</p><h1>{user.name}</h1><p>{user.role === "admin" ? "관리자" : "보호자 회원"}</p></div></header><section className="card settings-card"><h2>개인정보 설정</h2><form className="stack-form" onSubmit={saveProfile}><label>아이디<input value={user.username} disabled /></label><label>보호자 이름<input name="name" defaultValue={user.name} required /></label><label>휴대전화<input name="phone" defaultValue={user.phone} required /></label><button className="secondary">개인정보 저장</button></form></section>{children.length > 0 && <section className="card settings-card"><h2>자녀 정보</h2>{children.map((child) => <div className="child-profile" key={child.id}><b>{child.name}</b><span>{child.ageGroup}</span></div>)}</section>}<section className="card settings-card"><h2>알림 설정</h2>{([['booking','예약·취소'],['waitlist','대기 전환'],['notices','공지사항'],['chat','슬로우톡']] as const).map(([key, label]) => <label className="toggle-row" key={key}><span>{label}</span><input type="checkbox" checked={Boolean(settings[key])} onChange={(event) => saveNotifications({ ...settings, [key]: event.target.checked })} /></label>)}<div className="quiet-hours"><label>방해금지 시작<input type="time" value={settings.quietStart || ""} onChange={(event) => setSettings({ ...settings, quietStart: event.target.value })} /></label><label>방해금지 종료<input type="time" value={settings.quietEnd || ""} onChange={(event) => setSettings({ ...settings, quietEnd: event.target.value })} /></label><button className="secondary" onClick={() => saveNotifications()}>시간 저장</button></div></section><section className="card settings-card"><h2>비밀번호 변경</h2><form className="stack-form" onSubmit={changePassword}><label>현재 비밀번호<input type="password" name="currentPassword" required /></label><label>새 비밀번호<input type="password" name="newPassword" required /></label><button className="secondary">비밀번호 변경</button></form></section><div className="account-actions"><button onClick={async () => { await api("/api/v1/auth/logout", json("POST")); onLogout(); }}>로그아웃</button>{user.role !== "admin" && <button className="danger-text" onClick={async () => { if (!confirm("회원 탈퇴 후에는 로그인이 불가능합니다. 탈퇴할까요?")) return; await api("/api/v1/profile", json("DELETE")); onLogout(); }}>회원 탈퇴</button>}</div></section>;
}
